### ISSUE TITLE
Launcher won't start.

### ISSUE THREAD

**Issue by zackFlame** [gildedgames/aether-launcher#7]
When I try to start the new launcher, it gives me an error saying "A Java Exception has occurred."

**Comment by Lachney** [comment]
What version of Java are you running?  I would assume you're running Java 7.  Try upgrading to Java 8 and running our launcher.  It may fix your issue.

http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by zackFlame** [comment]
Thanks.
